# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
install! 'cocoapods', :integrate_targets => false

target 'CertPinner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CertPinner
  pod 'TrustKit',
    :git => 'https://github.com/ServiceMax-Engineering/TrustKit.git',
    :branch => 'pinning-toggle'
end
